### ISSUE TITLE
The index file encoding is incorrect on Windows

### ISSUE THREAD

**Issue by ccorpora** [joshbrunty/Indexer#1]
It seems like a small issue to open a pull request for so I am just writing it here. If you change line 34 to `open(index_path, 'w', encoding='utf-8')` the encoding on the _index.html_ file will change from the default _cp1252_ encoding on Windows and will now match the hard-coded encoding of _UTF-8_ in the HTML document. This issue was causing _UTF-8_ symbols to incorrectly display on Windows or cause the program to crash.

**Comment by joshbrunty** [comment]
Thanks for spotting that! Of course I'm a heavy Linux user (and tested/coded in Linux) so this issue totally slipped through the cracks in testing. Changed out _Line 34_ per your recommendation so hopefully that fixes the issue! Just let me know if it does continue to crash.
